repos:
  - repo: "https://github.com/pycqa/flake8"
    rev: "5.0.4"
    hooks:
      - id: "flake8"
        additional_dependencies:
          - "flake8-bugbear"
          - "flake8-builtins"
          - "pep8-naming"
          - "flake8-comprehensions"
          - "flake8-implicit-str-concat"
          - "flake8-requirements"
          - "flake8-docstrings"
  - repo: "https://github.com/pycqa/isort"
    rev: "5.12.0"
    hooks:
      - id: "isort"
  - repo: "https://github.com/psf/black"
    rev: "22.6.0"
    hooks:
      - id: "black"
  - repo: "https://github.com/pre-commit/mirrors-mypy"
    rev: "v0.971"
    hooks:
      - id: "mypy"
        additional_dependencies:
          - "types-setuptools"
          - "types-PyYAML"
          - "types-Markdown"
          - "types-requests"
