version: 2

build:
  os: ubuntu-22.04
  tools:
    - python: "3.9"
    - python: "3.10"
    - python: "3.11"
    - python: "3.12"

# Build documentation in the "docs/" directory with Sphinx.
sphinx:
  configuration: docs/conf.py

formats:
  - pdf
  - epub

python:
   install:
   - requirements: requirements.txt
   - requirements: requirements-docs.txt
